/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

//import com.itextpdf.text.BadElementException;
import control.SQLEmpleados;
import javax.swing.JOptionPane;
import modelo.Empleados;
import control.HuellaDigital;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author jack
 */
public class AgregarEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form AgregarEmpleados
     */
    Index index;
    private SQLEmpleados SQL = new SQLEmpleados(this);
    //HuellaDigital HUELLA = new HuellaDigital(this);
    public HuellaDigital HUELLA2;
    public File ARCHIVOIMAGEN;
    public void imagenPorDefecto() throws IOException{
        this.imagenEmpleado.setIcon(new ImageIcon("/imagenes/usuario_defecto.jfif"));
    }
   
    
    public AgregarEmpleados() {
        super("Nuevo Empleado");
        initComponents();
        this.BotonFoto.setEnabled(false);
        this.mensajeHuella.setEnabled(false);
        this.botonAgregarEmpleado.setEnabled(false);
        this.ACTIVARHUELLA.setEnabled(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(AgregarEmpleados.HIDE_ON_CLOSE);
        this.setResizable(false);
        SQL.obtenerTipoDocumento();
        SQL.obtenerSexo();
        //SQL.obtenerContrato();
        SQL.obtenerCargos();
        SQL.obtenerDepartamentos();
        //this.mostrarCampos(false);
    }   

    public void cerrarVentana(){
        this.setDefaultCloseOperation(AgregarEmpleados.HIDE_ON_CLOSE);
    }
    
    public void noCerrarVentana(){
        this.setDefaultCloseOperation(AgregarEmpleados.DO_NOTHING_ON_CLOSE);
    }
    
    
    private void limpiarCampos(){
        this.documento.setText("");
        this.primer_nombre.setText("");
        this.segundo_nombre.setText("");
        this.primerApellido.setText("");
        this.segundoApellido.setText("");
        this.telefono.setText("");
        this.direccion.setText("");
        this.correo.setText("");
        this.contraseña.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        primer_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        segundo_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        primerApellido = new javax.swing.JTextField();
        segundoApellido = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        tipoDocumento = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        DEPARTAMENTOS = new javax.swing.JComboBox<>();
        MUNICIPIOS = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        imagenEmpleado = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        LblMostrarHuella = new javax.swing.JLabel();
        BotonFoto = new javax.swing.JButton();
        botonAgregarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajeHuella = new javax.swing.JTextArea();
        ACTIVARHUELLA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Nuevo Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(primer_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, 20));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel1.setText("Primer apellido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel2.setText("Primer nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel1.add(segundo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 230, -1));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel3.setText("Segundo nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel4.setText("Segundo apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel6.setText("Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 82, -1));

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel7.setText("Municipio");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));
        jPanel1.add(primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 230, -1));
        jPanel1.add(segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 231, -1));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 230, 20));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 231, 20));

        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 230, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel8.setText("Tipo Documento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel9.setText("Documento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 80, 20));

        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });
        jPanel1.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 230, 20));

        jPanel1.add(tipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 230, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 549, -1, 17));

        jLabel16.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel16.setText("Correo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 82, -1));
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 231, 20));

        jLabel17.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel17.setText("Contraseña");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 230, 20));

        jLabel18.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel18.setText("Cargo");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        jPanel1.add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 231, -1));

        jLabel10.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel10.setText("Sexo");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, -1, -1));

        jLabel11.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel11.setText("Departamento");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        DEPARTAMENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPARTAMENTOSActionPerformed(evt);
            }
        });
        jPanel1.add(DEPARTAMENTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 500, 230, -1));

        jPanel1.add(MUNICIPIOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 540, 230, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        imagenEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/add_user.png"))); // NOI18N
        imagenEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagenEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Huella Digital", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMostrarHuella, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LblMostrarHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addContainerGap())
        );

        BotonFoto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BotonFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/explorer_folders_32px.png"))); // NOI18N
        BotonFoto.setText("Examinar");
        BotonFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFotoActionPerformed(evt);
            }
        });

        botonAgregarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonAgregarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/floppysave32px.png"))); // NOI18N
        botonAgregarEmpleado.setText("Agregar");
        botonAgregarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarEmpleadoActionPerformed(evt);
            }
        });

        mensajeHuella.setEditable(false);
        mensajeHuella.setColumns(20);
        mensajeHuella.setRows(5);
        jScrollPane1.setViewportView(mensajeHuella);

        ACTIVARHUELLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ACTIVARHUELLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fingerprint_32PX.png"))); // NOI18N
        ACTIVARHUELLA.setText("Iniciar Detección de Huella");
        ACTIVARHUELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTIVARHUELLAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ACTIVARHUELLA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(botonAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(BotonFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ACTIVARHUELLA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAgregarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarEmpleadoActionPerformed
        // TODO add your handling code here:   
        if(!this.documento.getText().equals("") && !this.primer_nombre.getText().equals("") && !this.segundo_nombre.getText().equals("") 
        && !this.primerApellido.getText().equals("") && !this.segundoApellido.getText().equals("") && 
        !this.telefono.getText().equals("") && !this.direccion.getText().equals("") && 
        !this.contraseña.getText().equals("")){          
                if(!SQL.validarEmpleado(this.documento.getText())){
                    if(this.ARCHIVOIMAGEN != null){
                        Empleados empleado = new Empleados(); 
                        empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                        empleado.setDOCUMENTO(this.documento.getText());
                        empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                        empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                        empleado.setPRIMER_APELLIDO(this.primerApellido.getText());
                        empleado.setSEGUNDO_APELLIDO(this.segundoApellido.getText());
                        empleado.setTELEFONO(this.telefono.getText());
                        empleado.setDIRECCION(this.direccion.getText());
                        empleado.setCORREO(this.correo.getText());           
                        empleado.setCONTRASENA(this.contraseña.getText());
                        empleado.setSEXO(this.sexo.getSelectedItem().toString());
                        empleado.setCARGO(this.cargo.getSelectedItem().toString());
                        String MUNICIPIO = this.MUNICIPIOS.getSelectedItem().toString();
                        SQL.ingresarEmpleados(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                        empleado.getDOCUMENTO(),empleado.getPRIMER_NOMBRE(),empleado.getSEGUNDO_NOMBRE(),
                        empleado.getPRIMER_APELLIDO(),empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO()
                        ,empleado.getDIRECCION(),empleado.getCORREO(),empleado.getCONTRASENA(),empleado.getCARGO(),
                        this.HUELLA2,this.ARCHIVOIMAGEN,MUNICIPIO);
                        this.limpiarCampos();
                        JOptionPane.showMessageDialog(null,"Empleado ingresado correctamente!");
                    }
                    else{
                        JOptionPane.showMessageDialog(null, "Debe seleccionar una imagen", "Mensaje",JOptionPane.WARNING_MESSAGE);
                    }
                    }else{
                        JOptionPane.showMessageDialog(null,"Ya existe un empleado con este documento");                
                    }
        }else{
            JOptionPane.showMessageDialog(null,"Debe diligenciar todos los campos");
        }       
    }//GEN-LAST:event_botonAgregarEmpleadoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        this.HUELLA.Iniciar();
//        this.HUELLA.start();
//        this.HUELLA.estadoHuellas();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void BotonFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFotoActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        archivo.setDialogTitle("Seleccionar imagen");
        archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(archivo.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){            
            File file  = archivo.getSelectedFile();
            if(file.getName().endsWith("jpeg") || file.getName().endsWith("jpg") || file.getName().endsWith("png")){
              this.ARCHIVOIMAGEN = file;
              ImageIcon imagen = new ImageIcon(file.getPath());
              System.out.println(file.getPath());
              this.imagenEmpleado.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(this.imagenEmpleado.getWidth(),
              this.imagenEmpleado.getHeight(),java.awt.Image.SCALE_DEFAULT)));
            }else{
                JOptionPane.showMessageDialog(null,"El archivo debe ser una imagen", "Mensaje", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_BotonFotoActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
//        if(this.documento.getText().equals("")){
//            JOptionPane.showMessageDialog(null,"Debe digitar un documento", "Mensaje", JOptionPane.WARNING_MESSAGE);
//        }else{
//            if(SQL.validarEmpleado(this.documento.getText())){
//                JOptionPane.showMessageDialog(null,"El usuario ya existe", "Mensaje", JOptionPane.WARNING_MESSAGE);
//            }else{
//                this.ACTIVARHUELLA.setEnabled(true);
//            }
//        }
    }//GEN-LAST:event_documentoActionPerformed

    private void ACTIVARHUELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTIVARHUELLAActionPerformed
        // TODO add your handling code here:
        int respuesta;
        respuesta = JOptionPane.showOptionDialog(null,"¿Esta seguro que desea continuar?","Mensaje", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(respuesta == JOptionPane.YES_NO_OPTION){
            if(!this.documento.getText().equals("") && !this.primer_nombre.getText().equals("") && !this.segundo_nombre.getText().equals("") 
        && !this.primerApellido.getText().equals("") && !this.segundoApellido.getText().equals("") && 
        !this.telefono.getText().equals("") && !this.direccion.getText().equals("") && 
        !this.contraseña.getText().equals("")){
                this.noCerrarVentana();
                this.ACTIVARHUELLA.setEnabled(false);
                this.LblMostrarHuella.setIcon(null);
                HuellaDigital HUELLA = new HuellaDigital(this);
                HUELLA.Iniciar();
                HUELLA.start();
                HUELLA.estadoHuellas();
            }else{
                 JOptionPane.showMessageDialog(null,"Debe llenar todos los datos del empleado", "Mensaje", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_ACTIVARHUELLAActionPerformed

    private void DEPARTAMENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPARTAMENTOSActionPerformed
        // TODO add your handling code here:
        this.MUNICIPIOS.removeAllItems();
        SQL.obtenerMunicipios(this.DEPARTAMENTOS.getSelectedItem().toString());
    }//GEN-LAST:event_DEPARTAMENTOSActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton ACTIVARHUELLA;
    public javax.swing.JButton BotonFoto;
    public javax.swing.JComboBox<String> DEPARTAMENTOS;
    public javax.swing.JLabel LblMostrarHuella;
    public javax.swing.JComboBox<String> MUNICIPIOS;
    public javax.swing.JButton botonAgregarEmpleado;
    public javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.JLabel imagenEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JTextArea mensajeHuella;
    private javax.swing.JTextField primerApellido;
    private javax.swing.JTextField primer_nombre;
    private javax.swing.JTextField segundoApellido;
    private javax.swing.JTextField segundo_nombre;
    public javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    public javax.swing.JComboBox<String> tipoDocumento;
    // End of variables declaration//GEN-END:variables
}
