/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.SQLEmpleados;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juliancc
 */
public class AgregarTipoCargos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarTipoDocumento
     */
    SQLEmpleados SQL = new SQLEmpleados(this);
    public DefaultTableModel TABLA;
    public AgregarTipoCargos(){
        TABLA = new DefaultTableModel(new Object []{"TIPO DE CARGOS DISPONIBLES"},0);
        initComponents();
        this.setDefaultCloseOperation(AgregarTipoCargos.HIDE_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        SQL.obtenerCargosVentanaActualizar();
    }
    
    public void limpiarTabla(){
        while(TABLA.getRowCount() > 0){
            for(int x = 0; x < TABLA.getRowCount();x++){
                TABLA.removeRow(x);
            }
            this.TABLATIPOCARGOS.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLATIPOCARGOS = new javax.swing.JTable();
        CAMPOEDITAR = new javax.swing.JTextField();
        BOTONEDITAR = new javax.swing.JButton();
        CAMPONUEVOCARGO = new javax.swing.JTextField();
        BOTONNUEVO = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TIPOS DE CARGOS");

        TABLATIPOCARGOS.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TABLATIPOCARGOS.setModel(TABLA);
        TABLATIPOCARGOS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TABLATIPOCARGOSMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(TABLATIPOCARGOS);

        BOTONEDITAR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BOTONEDITAR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save32px.png"))); // NOI18N
        BOTONEDITAR.setText("Actualizar");
        BOTONEDITAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONEDITARActionPerformed(evt);
            }
        });

        BOTONNUEVO.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BOTONNUEVO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/database.png"))); // NOI18N
        BOTONNUEVO.setText("Nuevo");
        BOTONNUEVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOTONNUEVOActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("Actualizar Cargo");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("Nuevo Cargo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CAMPOEDITAR, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                        .addComponent(CAMPONUEVOCARGO))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BOTONEDITAR, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(BOTONNUEVO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BOTONEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CAMPOEDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BOTONNUEVO)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CAMPONUEVOCARGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BOTONEDITARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONEDITARActionPerformed
        // TODO add your handling code here:
        if(!this.CAMPOEDITAR.getText().equals("")){
            String cargo = String.valueOf(this.TABLA.getValueAt(TABLATIPOCARGOS.getSelectedRow(),0));
            if(SQL.actualizarCargos(cargo,this.CAMPOEDITAR.getText())){
                this.CAMPOEDITAR.setText("");
                this.limpiarTabla();
                SQL.obtenerCargosVentanaActualizar();
                JOptionPane.showMessageDialog(null,"¡El cargo se ha actualizado correctamente!","Mensaje",JOptionPane.INFORMATION_MESSAGE);
        }
        }else{
            JOptionPane.showMessageDialog(null,"¡Debe seleccionar el cargo de la tabla para actualizar!","Mensaje",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_BOTONEDITARActionPerformed

    private void BOTONNUEVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOTONNUEVOActionPerformed
        // TODO add your handling code here:
        if(!this.CAMPONUEVOCARGO.getText().equals("")){
            if(SQL.consultarCargo(this.CAMPONUEVOCARGO.getText()) != true){
                String cargo = this.CAMPONUEVOCARGO.getText().toUpperCase();
                if(SQL.ingresarCargos(cargo)){
                    this.CAMPONUEVOCARGO.setText("");
                    this.limpiarTabla(); 
                    SQL.obtenerCargosVentanaActualizar();
                    JOptionPane.showMessageDialog(null,"¡El cargo se ha ingresado correctamente!","Mensaje",JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null,"¡Ya existe un cargo con este nombre!","Mensaje",JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null,"¡Debe digitar el cargo a ingresar!","Mensaje",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_BOTONNUEVOActionPerformed

    private void TABLATIPOCARGOSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLATIPOCARGOSMousePressed
        // TODO add your handling code here:
        this.CAMPOEDITAR.setText(String.valueOf(TABLA.getValueAt(this.TABLATIPOCARGOS.getSelectedRow(),0)));
    }//GEN-LAST:event_TABLATIPOCARGOSMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoCargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoCargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoCargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarTipoCargos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarTipoCargos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOTONEDITAR;
    private javax.swing.JButton BOTONNUEVO;
    private javax.swing.JTextField CAMPOEDITAR;
    private javax.swing.JTextField CAMPONUEVOCARGO;
    public javax.swing.JTable TABLATIPOCARGOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
