/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.SQLEmpleados;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import modelo.Empleados;

/**
 *
 * @author jack
 */
public class AgregarEmpleadosBackup extends javax.swing.JFrame {

    /**
     * Creates new form AgregarEmpleados
     */
    
   // SQLEmpleados SQL = new SQLEmpleados(this);    
    
    private void mostrarCampos(Boolean dato){
        this.labelcontrato.setVisible(dato);
        this.labeldescripcion.setVisible(dato);
        this.labelfecha.setVisible(dato);
        this.labelfechafinal.setVisible(dato);
        this.fechainicio.setVisible(dato);
        this.fechaterminacion.setVisible(dato);
        this.descripcionContrato.setVisible(dato);
        this.contrato.setVisible(dato);
    }
    
    public AgregarEmpleadosBackup() {
        super("Nuevo Empleado");
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(AgregarEmpleadosBackup.HIDE_ON_CLOSE);
        this.habilitarContratos.setEnabled(false);
        this.fechainicio.setEditable(false);
        this.fechaterminacion.setEditable(false);
        this.descripcionContrato.setEditable(false);
        this.setResizable(false);
        /*SQL.obtenerTipoDocumento();
        SQL.obtenerSexo();
        SQL.obtenerContrato();
        SQL.obtenerCargos();*/
        this.mostrarCampos(false);
    }   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        primer_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        segundo_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        primerApellido = new javax.swing.JTextField();
        segundoApellido = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        sexo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        tipoDocumento = new javax.swing.JComboBox<>();
        botonAgregarEmpleado = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        labelcontratacion = new javax.swing.JLabel();
        labelcontrato = new javax.swing.JLabel();
        contrato = new javax.swing.JComboBox<>();
        labeldescripcion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionContrato = new javax.swing.JTextPane();
        labelfechafinal = new javax.swing.JLabel();
        fechainicio = new javax.swing.JTextField();
        labelfecha = new javax.swing.JLabel();
        fechaterminacion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        habilitarContratos = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(primer_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 236, -1));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel1.setText("Primer apellido");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel2.setText("Primer nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 97, -1, -1));
        jPanel1.add(segundo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 231, -1));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel3.setText("Segundo nombre");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 97, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel4.setText("Segundo apellido");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 135, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel5.setText("Telefono");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 183, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel6.setText("Dirección");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 82, -1));

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel7.setText("Sexo");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 221, -1, -1));
        jPanel1.add(primerApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 236, -1));
        jPanel1.add(segundoApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 231, -1));
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 240, -1));
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 231, -1));

        jPanel1.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 240, -1));

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel8.setText("Tipo Documento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, -1, -1));

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel9.setText("Documento");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 54, -1, -1));
        jPanel1.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(533, 49, 231, -1));

        jPanel1.add(tipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 236, -1));

        botonAgregarEmpleado.setText("Agregar");
        botonAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(botonAgregarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 496, 207, 32));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 302, 800, 17));

        jLabel10.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
        jLabel10.setText("Datos personales");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        labelcontratacion.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
        labelcontratacion.setText("Contratación (Opcional)");
        jPanel1.add(labelcontratacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 325, -1, -1));

        labelcontrato.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        labelcontrato.setText("Contrato");
        jPanel1.add(labelcontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(59, 365, -1, -1));

        contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratoActionPerformed(evt);
            }
        });
        jPanel1.add(contrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 367, 164, -1));

        labeldescripcion.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        labeldescripcion.setText("Descripción");
        jPanel1.add(labeldescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 396, -1, -1));

        jScrollPane1.setViewportView(descripcionContrato);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 425, 780, 61));

        labelfechafinal.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        labelfechafinal.setText("Fecha finalización");
        jPanel1.add(labelfechafinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, -1, -1));
        jPanel1.add(fechainicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 365, 117, -1));

        labelfecha.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        labelfecha.setText("Fecha inicio");
        jPanel1.add(labelfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 370, -1, -1));
        jPanel1.add(fechaterminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 365, 113, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 549, -1, 17));

        jLabel16.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel16.setText("Correo");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 82, -1));
        jPanel1.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 231, -1));

        jLabel17.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel17.setText("Contraseña");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        jPanel1.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 240, -1));

        habilitarContratos.setText("Habilitar");
        habilitarContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habilitarContratosActionPerformed(evt);
            }
        });
        jPanel1.add(habilitarContratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 327, -1, -1));

        jLabel18.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel18.setText("Cargo");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        jPanel1.add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 231, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratoActionPerformed
        // TODO add your handling code here:
        //SQL.obtenerDatosContrato(this.contrato.getSelectedItem().toString());
    }//GEN-LAST:event_contratoActionPerformed

    private void habilitarContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habilitarContratosActionPerformed
        // TODO add your handling code here:
        if(this.habilitarContratos.isSelected()){            
            this.mostrarCampos(true);
        }else{
            this.mostrarCampos(false);
        }
        
        
    }//GEN-LAST:event_habilitarContratosActionPerformed

    private void botonAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarEmpleadoActionPerformed
        // TODO add your handling code here:   
        /*if(!this.documento.getText().equals("") && !this.primer_nombre.getText().equals("") && !this.segundo_nombre.getText().equals("") 
        && !this.primerApellido.getText().equals("") && !this.segundoApellido.getText().equals("") && 
        !this.telefono.getText().equals("") && !this.direccion.getText().equals("") && 
        !this.contraseña.getText().equals("")){            
            if(!this.habilitarContratos.isSelected()){
                if(!SQL.validarEmpleado(this.documento.getText())){
                        Empleados empleado = new Empleados();
                        empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                        empleado.setDOCUMENTO(this.documento.getText());
                        empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                        empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                        empleado.setPRIMER_APELLIDO(this.primerApellido.getText());
                        empleado.setSEGUNDO_APELLIDO(this.segundoApellido.getText());
                        empleado.setTELEFONO(this.telefono.getText());
                        empleado.setDIRECCION(this.direccion.getText());
                        empleado.setCORREO(this.correo.getText());           
                        empleado.setCONTRASENA(this.contraseña.getText());
                        empleado.setSEXO(this.sexo.getSelectedItem().toString());
                        empleado.setCARGO(this.cargo.getSelectedItem().toString());
                        SQL.ingresarEmpleados(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                        empleado.getDOCUMENTO(),empleado.getPRIMER_NOMBRE(),empleado.getSEGUNDO_NOMBRE(),
                        empleado.getPRIMER_APELLIDO(),empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO()
                        ,empleado.getDIRECCION(),empleado.getCORREO(),empleado.getCONTRASENA(),empleado.getCARGO());
                        JOptionPane.showMessageDialog(null,"Empleado ingresado correctamente!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Ya existe un empleado con este documento");                
                    }            
            }
                else{
                    if(!SQL.validarEmpleado(this.documento.getText())){
                        Empleados empleado = new Empleados();
                        empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                        empleado.setDOCUMENTO(this.documento.getText());
                        empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                        empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                        empleado.setPRIMER_APELLIDO(this.primerApellido.getText());
                        empleado.setSEGUNDO_APELLIDO(this.segundoApellido.getText());
                        empleado.setTELEFONO(this.telefono.getText());
                        empleado.setDIRECCION(this.direccion.getText());
                        empleado.setCORREO(this.correo.getText());           
                        empleado.setCONTRASENA(this.contraseña.getText());
                        empleado.setSEXO(this.sexo.getSelectedItem().toString());
                        empleado.setCARGO(this.cargo.getSelectedItem().toString());
                        String contrato_seleccionado = this.contrato.getSelectedItem().toString();
                        SQL.ingresarEmpleadosConContratos(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                        empleado.getDOCUMENTO(),empleado.getPRIMER_NOMBRE(),empleado.getSEGUNDO_NOMBRE(),
                        empleado.getPRIMER_APELLIDO(),empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO()
                        ,empleado.getDIRECCION(),empleado.getCORREO(),empleado.getCONTRASENA(),contrato_seleccionado, empleado.getCARGO());
                        JOptionPane.showMessageDialog(null,"Empleado ingresado correctamente!");
                    }else{
                        JOptionPane.showMessageDialog(null,"Ya existe un empleado con este documento");                
                    }
                }
        }else{
            JOptionPane.showMessageDialog(null,"Debe diligenciar los campos obligatorios");
        }   */    
    }//GEN-LAST:event_botonAgregarEmpleadoActionPerformed

  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadosBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadosBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadosBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEmpleadosBackup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEmpleadosBackup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarEmpleado;
    public javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField contraseña;
    public javax.swing.JComboBox<String> contrato;
    private javax.swing.JTextField correo;
    public javax.swing.JTextPane descripcionContrato;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    public javax.swing.JTextField fechainicio;
    public javax.swing.JTextField fechaterminacion;
    private javax.swing.JCheckBox habilitarContratos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelcontratacion;
    private javax.swing.JLabel labelcontrato;
    private javax.swing.JLabel labeldescripcion;
    private javax.swing.JLabel labelfecha;
    private javax.swing.JLabel labelfechafinal;
    private javax.swing.JTextField primerApellido;
    private javax.swing.JTextField primer_nombre;
    private javax.swing.JTextField segundoApellido;
    private javax.swing.JTextField segundo_nombre;
    public javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    public javax.swing.JComboBox<String> tipoDocumento;
    // End of variables declaration//GEN-END:variables
}
