/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import control.SQLContratos;
import modelo.Contratos;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jack
 */
public class CrearContratos extends javax.swing.JFrame {

private String temp_nombre_contrato = "";
private SQLContratos SQL = new SQLContratos(this);
public DefaultTableModel TABLACREARCONTRATOS;
DateFormat DF = new SimpleDateFormat("yyyy-MM-dd");
Contratos contrato = new Contratos();
    /**
     * Creates new form CrearContratos
     */

     private void editarCampos(Boolean datum){
       this.nombrecontrato.setEditable(datum);
       this.fecha_inicio.setEnabled(datum);
       this.fecha_finalizacion.setEnabled(datum);
       this.descripcion.setEditable(datum);
    }
     
         public void borrarFilasTabla(){
            while(this.TABLACREARCONTRATOS.getRowCount()>0){
                for(int j=0;j<this.TABLACREARCONTRATOS.getRowCount();j++){
                        this.TABLACREARCONTRATOS.removeRow(j);
                }
            this.tablaContratos.repaint();
            }
        }
     
     
    private void borrarCeldas(){
       this.nombrecontrato.setText("");
       this.fecha_inicio.cleanup();
       this.fecha_finalizacion.cleanup();
       this.descripcion.setText("");
    }


    public CrearContratos() {
        super("Crear contratos"); 
        TABLACREARCONTRATOS =   new DefaultTableModel(new Object[]{"Contrato","Fecha inicio","Fecha terminación","Descripción"},0);
        initComponents();     
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        SQL.obtenerContratos();
         this.boton_actualizar.setEnabled(false);
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        nombrecontrato = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaContratos = new javax.swing.JTable();
        nuevo_contrato = new javax.swing.JButton();
        boton_actualizar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        fecha_inicio = new com.toedter.calendar.JDateChooser();
        fecha_finalizacion = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Bitstream Vera Serif", 1, 15)); // NOI18N
        jLabel12.setText("Creación de contratos");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel15.setText("Fecha inicio");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel14.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel14.setText("Fecha finalización");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel13.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel13.setText("Descripción");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 549, 10));
        getContentPane().add(nombrecontrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 361, -1));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 361, -1));

        tablaContratos.setModel(TABLACREARCONTRATOS);
        tablaContratos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaContratosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaContratos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 530, 170));

        nuevo_contrato.setText("Nuevo");
        nuevo_contrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_contratoActionPerformed(evt);
            }
        });
        getContentPane().add(nuevo_contrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 120, -1));

        boton_actualizar.setText("Actualizar");
        boton_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, 120, -1));

        jLabel16.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel16.setText("Nombre Contrato");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));
        getContentPane().add(fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 360, -1));
        getContentPane().add(fecha_finalizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo_contratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_contratoActionPerformed
        // TODO add your handling code here:           
        
        if(!this.nombrecontrato.getText().equals("") && this.fecha_inicio.getDate() != null 
           && this.fecha_finalizacion.getDate() != null && !this.descripcion.getText().equals("")){
            if(this.fecha_inicio.getDate().before(this.fecha_finalizacion.getDate())){                
                contrato.setNombreContrato(this.nombrecontrato.getText());
                contrato.setFechaInicial(DF.format(this.fecha_inicio.getDate()));
                contrato.setFechaFinal(DF.format(this.fecha_finalizacion.getDate()));
                contrato.setDescripcion(this.descripcion.getText());                
                if(SQL.insertarContrato(contrato.getNombreContrato(),contrato.getFechaInicial(),contrato.getFechaFinal(),contrato.getDescripcion())){
                    this.borrarCeldas();
                    this.borrarFilasTabla();
                    SQL.obtenerContratos();
                    JOptionPane.showMessageDialog(null,"Contrato ingresado correctamente!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }                
            }else{
                JOptionPane.showMessageDialog(null,"La fecha de terminación del contrato debe ser mayor a la fecha de inicio", "Error", JOptionPane.WARNING_MESSAGE);
            }                
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_nuevo_contratoActionPerformed

    private void boton_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_actualizarActionPerformed
        // TODO add your handling code here:
        if(!this.nombrecontrato.getText().equals("") && this.fecha_inicio.getDate() != null 
           && this.fecha_finalizacion.getDate() != null && !this.descripcion.getText().equals("")){
            if(this.fecha_inicio.getDate().before(this.fecha_finalizacion.getDate())){                
                contrato.setNombreContrato(this.nombrecontrato.getText());
                contrato.setFechaInicial(DF.format(this.fecha_inicio.getDate()));
                contrato.setFechaFinal(DF.format(this.fecha_finalizacion.getDate()));
                contrato.setDescripcion(this.descripcion.getText());
                if(SQL.actualizarContratos(this.temp_nombre_contrato,contrato.getNombreContrato(),contrato.getFechaInicial(),contrato.getFechaFinal(), contrato.getDescripcion())){
                    this.borrarCeldas();
                    this.borrarFilasTabla();
                    SQL.obtenerContratos();
                    JOptionPane.showMessageDialog(null,"Contrato actualizado correctamente!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                }               
            }else{
                JOptionPane.showMessageDialog(null,"La fecha de terminación del contrato debe ser mayor a la fecha de inicio", "Error", JOptionPane.WARNING_MESSAGE);
            }                   
        }else{
            JOptionPane.showMessageDialog(null,"Debe llenar todos los campos", "Error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_boton_actualizarActionPerformed

    private void tablaContratosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContratosMouseClicked
        // TODO add your handling code here:
        this.temp_nombre_contrato = this.TABLACREARCONTRATOS.getValueAt(this.tablaContratos.getSelectedRow(),0).toString();        
        Object nombreContrato = this.TABLACREARCONTRATOS.getValueAt(this.tablaContratos.getSelectedRow(),0);
        Object fechaInicio = this.TABLACREARCONTRATOS.getValueAt(this.tablaContratos.getSelectedRow(),1);
        Object fechaFinalizacion = this.TABLACREARCONTRATOS.getValueAt(this.tablaContratos.getSelectedRow(),2);
        Object descripcionContrato = this.TABLACREARCONTRATOS.getValueAt(this.tablaContratos.getSelectedRow(),3);
        this.nombrecontrato.setText(nombreContrato.toString());
        this.descripcion.setText(descripcionContrato.toString());
        try{
            this.fecha_inicio.setDate(DF.parse(fechaInicio.toString()));
            this.fecha_finalizacion.setDate(DF.parse(fechaFinalizacion.toString()));
            this.boton_actualizar.setEnabled(true);
            
        }catch(ParseException ex){
            JOptionPane.showMessageDialog(null,ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_tablaContratosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearContratos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearContratos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_actualizar;
    private javax.swing.JTextArea descripcion;
    private com.toedter.calendar.JDateChooser fecha_finalizacion;
    private com.toedter.calendar.JDateChooser fecha_inicio;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nombrecontrato;
    private javax.swing.JButton nuevo_contrato;
    private javax.swing.JTable tablaContratos;
    // End of variables declaration//GEN-END:variables
}
