/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.HuellaDigitalEditarEmpleados;
import control.SQLEmpleados;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import modelo.Empleados;

/**
 *
 * @author jack
 */
public class EditarEmpleados extends javax.swing.JFrame {

    SQLEmpleados SQL = new SQLEmpleados(this);
    String documento_anterior;
    //HuellaDigitalEditarEmpleados HUELLA = new HuellaDigitalEditarEmpleados(this);
    public HuellaDigitalEditarEmpleados HUELLA2;
    public File ARCHIVOIMAGEN;

    /**
     * Creates new form EditarEmpleados
     */
    public EditarEmpleados() {
        super("Editar Empleados");
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        this.mensajeHuella.setEditable(false);
        this.BTNBUSCARIMAGEN.setEnabled(false);
        this.botonActualizarEmpleado.setEnabled(false);
        this.setDefaultCloseOperation(EditarEmpleados.HIDE_ON_CLOSE);
        SQL.obtenerSexoActualizacion();
        SQL.obtenerCargosActualizar();
        SQL.obtenerTipoDocumentoActualizar();
        SQL.obtenerDepartamentosEditarEmpleados();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public void cerrarVentana() {
        this.setDefaultCloseOperation(EditarEmpleados.HIDE_ON_CLOSE);
    }

    public void noCerrarVentana() {
        this.setDefaultCloseOperation(EditarEmpleados.DO_NOTHING_ON_CLOSE);
    }

    private void limpiarCampos() {
        this.documento.setText("");
        this.primer_nombre.setText("");
        this.segundo_nombre.setText("");
        this.primer_apellido.setText("");
        this.segundo_apellido.setText("");
        this.direccion.setText("");
        this.telefono.setText("");
        this.correo.setText("");
        this.contraseña.setText("");
        this.LblMostrarHuella.setIcon(null);
        this.LblfotoPerfil.setIcon(null);
        this.botonActualizarEmpleado.setEnabled(false);
        this.BTNBUSCARIMAGEN.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        primer_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        primer_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        segundo_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundo_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DEPARTAMENTOS = new javax.swing.JComboBox<>();
        MUNICIPIOS = new javax.swing.JComboBox<>();
        BTNBUSCARIMAGEN = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        LblMostrarHuella = new javax.swing.JLabel();
        DETECCIONHUELLA = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajeHuella = new javax.swing.JTextArea();
        botonActualizarEmpleado = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        LblfotoPerfil = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Empleado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel8.setText("Tipo Documento");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 39, -1, -1));

        jPanel2.add(tipoDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 41, 230, -1));

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel2.setText("Primer nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 118, -1, -1));

        primer_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(primer_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 118, 230, 28));

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel1.setText("Primer apellido");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 199, -1, -1));

        primer_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(primer_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 204, 230, 27));

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel5.setText("Telefono");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 319, -1, -1));

        telefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 318, 230, 30));

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel7.setText("Sexo");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 440, -1, -1));

        jPanel2.add(sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 226, -1));

        jLabel17.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel17.setText("Contraseña");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 559, -1, -1));

        contraseña.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 550, 226, 30));

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel9.setText("Documento");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 72, 89, 28));

        documento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });
        jPanel2.add(documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 72, 230, 28));

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel3.setText("Segundo nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 156, -1, -1));

        segundo_nombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(segundo_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 159, 230, 30));

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel4.setText("Segundo apellido");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 237, -1, -1));

        segundo_apellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(segundo_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 242, 230, 27));

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel6.setText("Dirección");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 275, 82, -1));

        direccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 280, 230, 27));

        jLabel16.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel16.setText("Correo");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 363, 82, 32));

        correo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 363, 230, 28));

        jLabel18.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel18.setText("Cargo");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 401, -1, -1));

        jPanel2.add(cargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 226, -1));

        jLabel11.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel11.setText("Departamento");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 479, -1, -1));

        jLabel12.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel12.setText("Municipio");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 518, -1, -1));

        DEPARTAMENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPARTAMENTOSActionPerformed(evt);
            }
        });
        jPanel2.add(DEPARTAMENTOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 226, -1));

        jPanel2.add(MUNICIPIOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 226, -1));

        BTNBUSCARIMAGEN.setBackground(new java.awt.Color(255, 255, 255));
        BTNBUSCARIMAGEN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNBUSCARIMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/explorer_folders_32px.png"))); // NOI18N
        BTNBUSCARIMAGEN.setText("Examinar");
        BTNBUSCARIMAGEN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNBUSCARIMAGEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARIMAGENActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Huella Digital", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMostrarHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblMostrarHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        DETECCIONHUELLA.setBackground(new java.awt.Color(255, 255, 255));
        DETECCIONHUELLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DETECCIONHUELLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fingerprint_32PX.png"))); // NOI18N
        DETECCIONHUELLA.setText("Iniciar Detección de Huella");
        DETECCIONHUELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETECCIONHUELLAActionPerformed(evt);
            }
        });

        mensajeHuella.setColumns(20);
        mensajeHuella.setRows(5);
        jScrollPane1.setViewportView(mensajeHuella);

        botonActualizarEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        botonActualizarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonActualizarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save32px.png"))); // NOI18N
        botonActualizarEmpleado.setText("Actualizar");
        botonActualizarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarEmpleadoActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(246, 71, 71));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("EDITAR DATOS EMPLEADO");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        LblfotoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblfotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_user.png"))); // NOI18N
        LblfotoPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(DETECCIONHUELLA, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                                            .addComponent(BTNBUSCARIMAGEN, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(LblfotoPerfil))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(botonActualizarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(LblfotoPerfil)
                        .addGap(8, 8, 8)
                        .addComponent(BTNBUSCARIMAGEN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(DETECCIONHUELLA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonActualizarEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarEmpleadoActionPerformed
        // TODO add your handling code here:
        if (!this.documento.getText().equals("") && !this.primer_nombre.getText().equals("") && !this.segundo_nombre.getText().equals("")
                && !this.primer_apellido.getText().equals("") && !this.segundo_apellido.getText().equals("")
                && !this.telefono.getText().equals("") && !this.direccion.getText().equals("")
                && !this.contraseña.getText().equals("")) {
            if (SQL.validarEmpleado(this.documento.getText())) {
                if (this.ARCHIVOIMAGEN != null) {
                    Empleados empleado = new Empleados();
                    empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                    empleado.setDOCUMENTO(this.documento.getText());
                    empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                    empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                    empleado.setPRIMER_APELLIDO(this.primer_apellido.getText());
                    empleado.setSEGUNDO_APELLIDO(this.segundo_apellido.getText());
                    empleado.setTELEFONO(this.telefono.getText());
                    empleado.setDIRECCION(this.direccion.getText());
                    empleado.setCORREO(this.correo.getText());
                    empleado.setCONTRASENA(this.contraseña.getText());
                    empleado.setSEXO(this.sexo.getSelectedItem().toString());
                    empleado.setCARGO(this.cargo.getSelectedItem().toString());
                    SQL.ActualizarEmpleados(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                            empleado.getDOCUMENTO(), empleado.getPRIMER_NOMBRE(), empleado.getSEGUNDO_NOMBRE(),
                            empleado.getPRIMER_APELLIDO(), empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO(),
                             empleado.getDIRECCION(), empleado.getCORREO(), empleado.getCONTRASENA(), empleado.getCARGO(),
                            this.documento_anterior, this.HUELLA2, this.ARCHIVOIMAGEN);
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente!");
                    this.limpiarCampos();
                } else {
                    Empleados empleado = new Empleados();
                    empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                    empleado.setDOCUMENTO(this.documento.getText());
                    empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                    empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                    empleado.setPRIMER_APELLIDO(this.primer_apellido.getText());
                    empleado.setSEGUNDO_APELLIDO(this.segundo_apellido.getText());
                    empleado.setTELEFONO(this.telefono.getText());
                    empleado.setDIRECCION(this.direccion.getText());
                    empleado.setCORREO(this.correo.getText());
                    empleado.setCONTRASENA(this.contraseña.getText());
                    empleado.setSEXO(this.sexo.getSelectedItem().toString());
                    empleado.setCARGO(this.cargo.getSelectedItem().toString());
                    SQL.ActualizarEmpleadosSinImagen(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                            empleado.getDOCUMENTO(), empleado.getPRIMER_NOMBRE(), empleado.getSEGUNDO_NOMBRE(),
                            empleado.getPRIMER_APELLIDO(), empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO(),
                             empleado.getDIRECCION(), empleado.getCORREO(), empleado.getCONTRASENA(), empleado.getCARGO(),
                            this.documento_anterior, this.HUELLA2);
                    JOptionPane.showMessageDialog(null, "Datos actualizados correctamente!");
                    this.limpiarCampos();
                }
            } else {
                JOptionPane.showMessageDialog(null, "No existe un empleado con este documento");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe digitar el documento del empleado");
        }
    }//GEN-LAST:event_botonActualizarEmpleadoActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
        if (!this.documento.getText().equals("")) {
            if (SQL.validarEmpleado(documento.getText())) {
                String array[] = new String[11];
                array = SQL.obtenerDatosUsuarioEditar(this.documento.getText());
                this.documento_anterior = array[1];
                this.primer_nombre.setText(array[2]);
                this.segundo_nombre.setText(array[3]);
                this.primer_apellido.setText(array[4]);
                this.segundo_apellido.setText(array[5]);
                this.direccion.setText(array[6]);
                this.telefono.setText(array[7]);
                this.correo.setText(array[8]);
                this.contraseña.setText(array[11]);
                SQL.obtenerFotoEditarPerfil(documento.getText());
            } else {
                JOptionPane.showMessageDialog(null, "No existe un empleado con este documento");
            }
        }

    }//GEN-LAST:event_documentoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        this.HUELLA.Iniciar();
//        this.HUELLA.start();
//        this.HUELLA.estadoHuellas();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        this.HUELLA.stop();
    }//GEN-LAST:event_formWindowClosed

    private void BTNBUSCARIMAGENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARIMAGENActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        archivo.setDialogTitle("Seleccionar imagen");
        archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if (archivo.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = archivo.getSelectedFile();
            if (file.getName().endsWith("jpeg") || file.getName().endsWith("jpg") || file.getName().endsWith("png")) {
                this.ARCHIVOIMAGEN = file;
                ImageIcon imagen = new ImageIcon(file.getPath());
                System.out.println(file.getPath());
                this.LblfotoPerfil.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(this.LblfotoPerfil.getWidth(),
                        this.LblfotoPerfil.getHeight(), Image.SCALE_DEFAULT)));
            } else {
                JOptionPane.showMessageDialog(null, "El archivo debe ser una imagen", "Mensaje", JOptionPane.WARNING_MESSAGE);
            }
        }

    }//GEN-LAST:event_BTNBUSCARIMAGENActionPerformed

    private void DETECCIONHUELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETECCIONHUELLAActionPerformed
        // TODO add your handling code here:
        int respuesta;
        respuesta = JOptionPane.showOptionDialog(null, "¿Esta seguro que desea continuar?", "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            if (!this.documento.getText().equals("")) {
                this.DETECCIONHUELLA.setEnabled(false);
                this.noCerrarVentana();
                HuellaDigitalEditarEmpleados HUELLA = new HuellaDigitalEditarEmpleados(this);
                HUELLA.documento = this.documento.getText();
                HUELLA.Iniciar();
                HUELLA.start();
                HUELLA.estadoHuellas();
                this.DETECCIONHUELLA.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Debe digitar el documento del empleado", "Mensaje", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DETECCIONHUELLAActionPerformed

    private void DEPARTAMENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPARTAMENTOSActionPerformed
        // TODO add your handling code here:
        this.MUNICIPIOS.removeAllItems();
        SQL.obtenerMunicipiosEditarEmpleados(this.DEPARTAMENTOS.getSelectedItem().toString());
    }//GEN-LAST:event_DEPARTAMENTOSActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel13MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNBUSCARIMAGEN;
    public javax.swing.JComboBox<String> DEPARTAMENTOS;
    public javax.swing.JButton DETECCIONHUELLA;
    public javax.swing.JLabel LblMostrarHuella;
    public javax.swing.JLabel LblfotoPerfil;
    public javax.swing.JComboBox<String> MUNICIPIOS;
    public javax.swing.JButton botonActualizarEmpleado;
    public javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea mensajeHuella;
    private javax.swing.JTextField primer_apellido;
    private javax.swing.JTextField primer_nombre;
    private javax.swing.JTextField segundo_apellido;
    private javax.swing.JTextField segundo_nombre;
    public javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    public javax.swing.JComboBox<String> tipoDocumento;
    // End of variables declaration//GEN-END:variables
}
