/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.HuellaDigitalEditarEmpleados;
import control.SQLEmpleados;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import modelo.Empleados;

/**
 *
 * @author jack
 */
public class EditarEmpleados extends javax.swing.JFrame{

    SQLEmpleados SQL = new SQLEmpleados(this);
    String documento_anterior;
    //HuellaDigitalEditarEmpleados HUELLA = new HuellaDigitalEditarEmpleados(this);
    public HuellaDigitalEditarEmpleados HUELLA2;
    public File ARCHIVOIMAGEN;
    /**
     * Creates new form EditarEmpleados
     */
    public EditarEmpleados() {
        super("Editar Empleados");
        initComponents();
        this.mensajeHuella.setEditable(false);
        this.BTNBUSCARIMAGEN.setEnabled(false);
        this.botonActualizarEmpleado.setEnabled(false);
        this.setDefaultCloseOperation(EditarEmpleados.HIDE_ON_CLOSE);
        SQL.obtenerSexoActualizacion();
        SQL.obtenerCargosActualizar();
        SQL.obtenerTipoDocumentoActualizar();
        SQL.obtenerDepartamentosEditarEmpleados();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }
    
    public void cerrarVentana(){
        this.setDefaultCloseOperation(EditarEmpleados.HIDE_ON_CLOSE);
    }
    
    public void noCerrarVentana(){
        this.setDefaultCloseOperation(EditarEmpleados.DO_NOTHING_ON_CLOSE);
    }
    
    private void limpiarCampos(){
        this.documento.setText("");
        this.primer_nombre.setText("");
        this.segundo_nombre.setText("");
        this.primer_apellido.setText("");
        this.segundo_apellido.setText("");
        this.direccion.setText("");
        this.telefono.setText("");
        this.correo.setText("");
        this.contraseña.setText("");
        this.LblMostrarHuella.setIcon(null);
        this.LblfotoPerfil.setIcon(null);
        this.botonActualizarEmpleado.setEnabled(false);
        this.BTNBUSCARIMAGEN.setEnabled(false);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tipoDocumento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        primer_nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        primer_apellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sexo = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        segundo_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        segundo_apellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        correo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DEPARTAMENTOS = new javax.swing.JComboBox<>();
        MUNICIPIOS = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        LblfotoPerfil = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LblMostrarHuella = new javax.swing.JLabel();
        BTNBUSCARIMAGEN = new javax.swing.JButton();
        botonActualizarEmpleado = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajeHuella = new javax.swing.JTextArea();
        DETECCIONHUELLA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("DejaVu Serif", 1, 15)); // NOI18N
        jLabel10.setText("Datos personales");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 10, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editar Empleado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel8.setText("Tipo Documento");

        jLabel2.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel2.setText("Primer nombre");

        jLabel1.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel1.setText("Primer apellido");

        jLabel5.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel7.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel7.setText("Sexo");

        jLabel17.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel17.setText("Contraseña");

        jLabel9.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel9.setText("Documento");

        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel3.setText("Segundo nombre");

        jLabel4.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel4.setText("Segundo apellido");

        jLabel6.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel6.setText("Dirección");

        jLabel16.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel16.setText("Correo");

        jLabel18.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel18.setText("Cargo");

        jLabel11.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel11.setText("Departamento");

        jLabel12.setFont(new java.awt.Font("Bitstream Vera Serif", 0, 15)); // NOI18N
        jLabel12.setText("Municipio");

        DEPARTAMENTOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEPARTAMENTOSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tipoDocumento, 0, 223, Short.MAX_VALUE)
                            .addComponent(documento)
                            .addComponent(primer_nombre))
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(segundo_nombre)
                                    .addComponent(primer_apellido)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(17, 17, 17)
                                .addComponent(segundo_apellido))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(139, 139, 139)
                                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(correo)
                                    .addComponent(cargo, 0, 225, Short.MAX_VALUE)
                                    .addComponent(direccion)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sexo, 0, 226, Short.MAX_VALUE)
                                    .addComponent(DEPARTAMENTOS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MUNICIPIOS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(24, 24, 24))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(primer_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(segundo_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(primer_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(segundo_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(correo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(DEPARTAMENTOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(MUNICIPIOS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 400, 600));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Foto Empleado", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        LblfotoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblfotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/update_user.png"))); // NOI18N
        LblfotoPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblfotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblfotoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 270, 290));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Huella Digital", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMostrarHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblMostrarHuella, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 270, 220));

        BTNBUSCARIMAGEN.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNBUSCARIMAGEN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/explorer_folders_32px.png"))); // NOI18N
        BTNBUSCARIMAGEN.setText("Examinar");
        BTNBUSCARIMAGEN.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BTNBUSCARIMAGEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBUSCARIMAGENActionPerformed(evt);
            }
        });
        jPanel1.add(BTNBUSCARIMAGEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 270, 40));

        botonActualizarEmpleado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonActualizarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/save32px.png"))); // NOI18N
        botonActualizarEmpleado.setText("Actualizar");
        botonActualizarEmpleado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonActualizarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarEmpleadoActionPerformed(evt);
            }
        });
        jPanel1.add(botonActualizarEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 730, 188, 50));

        mensajeHuella.setColumns(20);
        mensajeHuella.setRows(5);
        jScrollPane1.setViewportView(mensajeHuella);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 680, 70));

        DETECCIONHUELLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DETECCIONHUELLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fingerprint_32PX.png"))); // NOI18N
        DETECCIONHUELLA.setText("Iniciar Detección de Huella");
        DETECCIONHUELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETECCIONHUELLAActionPerformed(evt);
            }
        });
        jPanel1.add(DETECCIONHUELLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarEmpleadoActionPerformed
        // TODO add your handling code here:
        if(!this.documento.getText().equals("") && !this.primer_nombre.getText().equals("") && !this.segundo_nombre.getText().equals("")
            && !this.primer_apellido.getText().equals("") && !this.segundo_apellido.getText().equals("") &&
            !this.telefono.getText().equals("") && !this.direccion.getText().equals("") &&
            !this.contraseña.getText().equals("")){            
                if(SQL.validarEmpleado(this.documento.getText())){
                    if(this.ARCHIVOIMAGEN != null){
                    Empleados empleado = new Empleados();
                    empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                    empleado.setDOCUMENTO(this.documento.getText());
                    empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                    empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                    empleado.setPRIMER_APELLIDO(this.primer_apellido.getText());
                    empleado.setSEGUNDO_APELLIDO(this.segundo_apellido.getText());
                    empleado.setTELEFONO(this.telefono.getText());
                    empleado.setDIRECCION(this.direccion.getText());
                    empleado.setCORREO(this.correo.getText());
                    empleado.setCONTRASENA(this.contraseña.getText());
                    empleado.setSEXO(this.sexo.getSelectedItem().toString());
                    empleado.setCARGO(this.cargo.getSelectedItem().toString());
                    SQL.ActualizarEmpleados(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                        empleado.getDOCUMENTO(),empleado.getPRIMER_NOMBRE(),empleado.getSEGUNDO_NOMBRE(),
                        empleado.getPRIMER_APELLIDO(),empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO()
                        ,empleado.getDIRECCION(),empleado.getCORREO(),empleado.getCONTRASENA(),empleado.getCARGO(),
                        this.documento_anterior,this.HUELLA2,this.ARCHIVOIMAGEN);
                    JOptionPane.showMessageDialog(null,"Datos actualizados correctamente!");
                    this.limpiarCampos();
                }else{                        
                    Empleados empleado = new Empleados();
                    empleado.setTIPO_DOCUMENTO(this.tipoDocumento.getSelectedItem().toString());
                    empleado.setDOCUMENTO(this.documento.getText());
                    empleado.setPRIMER_NOMBRE(this.primer_nombre.getText());
                    empleado.setSEGUNDO_NOMBRE(this.segundo_nombre.getText());
                    empleado.setPRIMER_APELLIDO(this.primer_apellido.getText());
                    empleado.setSEGUNDO_APELLIDO(this.segundo_apellido.getText());
                    empleado.setTELEFONO(this.telefono.getText());
                    empleado.setDIRECCION(this.direccion.getText());
                    empleado.setCORREO(this.correo.getText());
                    empleado.setCONTRASENA(this.contraseña.getText());
                    empleado.setSEXO(this.sexo.getSelectedItem().toString());
                    empleado.setCARGO(this.cargo.getSelectedItem().toString());
                    SQL.ActualizarEmpleadosSinImagen(empleado.getSEXO(), empleado.getTIPO_DOCUMENTO(),
                        empleado.getDOCUMENTO(),empleado.getPRIMER_NOMBRE(),empleado.getSEGUNDO_NOMBRE(),
                        empleado.getPRIMER_APELLIDO(),empleado.getSEGUNDO_APELLIDO(), empleado.getTELEFONO()
                        ,empleado.getDIRECCION(),empleado.getCORREO(),empleado.getCONTRASENA(),empleado.getCARGO(),
                        this.documento_anterior,this.HUELLA2);
                    JOptionPane.showMessageDialog(null,"Datos actualizados correctamente!");
                    this.limpiarCampos();
                 }
                }else{
                    JOptionPane.showMessageDialog(null,"No existe un empleado con este documento");
                }
        }else{
            JOptionPane.showMessageDialog(null,"Debe digitar el documento del empleado");
        }
    }//GEN-LAST:event_botonActualizarEmpleadoActionPerformed

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
        if(!this.documento.getText().equals("")){
            if(SQL.validarEmpleado(documento.getText())){
                String array [] = new String [11];
                array = SQL.obtenerDatosUsuarioEditar(this.documento.getText());
                this.documento_anterior = array[1];
                this.primer_nombre.setText(array[2]);
                this.segundo_nombre.setText(array[3]);
                this.primer_apellido.setText(array[4]);
                this.segundo_apellido.setText(array[5]);
                this.direccion.setText(array[6]);
                this.telefono.setText(array[7]);
                this.correo.setText(array[8]); 
                this.contraseña.setText(array[11]);
                SQL.obtenerFotoEditarPerfil(documento.getText());
            }else{
                JOptionPane.showMessageDialog(null,"No existe un empleado con este documento");
            }
        }
        
    }//GEN-LAST:event_documentoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        this.HUELLA.Iniciar();
//        this.HUELLA.start();
//        this.HUELLA.estadoHuellas();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
//        this.HUELLA.stop();
    }//GEN-LAST:event_formWindowClosed

    private void BTNBUSCARIMAGENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBUSCARIMAGENActionPerformed
        // TODO add your handling code here:
        JFileChooser archivo = new JFileChooser();
        archivo.setDialogTitle("Seleccionar imagen");
        archivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        if(archivo.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){            
              File file  = archivo.getSelectedFile();
            if(file.getName().endsWith("jpeg") || file.getName().endsWith("jpg") || file.getName().endsWith("png")){
              this.ARCHIVOIMAGEN = file;
              ImageIcon imagen = new ImageIcon(file.getPath());
              System.out.println(file.getPath());
              this.LblfotoPerfil.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(this.LblfotoPerfil.getWidth(),
              this.LblfotoPerfil.getHeight(),Image.SCALE_DEFAULT)));
            }else{
                JOptionPane.showMessageDialog(null,"El archivo debe ser una imagen", "Mensaje", JOptionPane.WARNING_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_BTNBUSCARIMAGENActionPerformed

    private void DETECCIONHUELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETECCIONHUELLAActionPerformed
        // TODO add your handling code here:
        int respuesta;
        respuesta = JOptionPane.showOptionDialog(null,"¿Esta seguro que desea continuar?","Mensaje", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE,null,null,null);
        if(respuesta == JOptionPane.YES_NO_OPTION){
        if(!this.documento.getText().equals("")){
            this.DETECCIONHUELLA.setEnabled(false);
            this.noCerrarVentana();
            HuellaDigitalEditarEmpleados HUELLA = new HuellaDigitalEditarEmpleados(this);
            HUELLA.documento = this.documento.getText();
            HUELLA.Iniciar();
            HUELLA.start();
            HUELLA.estadoHuellas();
            this.DETECCIONHUELLA.setEnabled(false);
        }else{
             JOptionPane.showMessageDialog(null,"Debe digitar el documento del empleado","Mensaje",JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_DETECCIONHUELLAActionPerformed

    private void DEPARTAMENTOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEPARTAMENTOSActionPerformed
        // TODO add your handling code here:
        this.MUNICIPIOS.removeAllItems();
       SQL.obtenerMunicipiosEditarEmpleados(this.DEPARTAMENTOS.getSelectedItem().toString());
    }//GEN-LAST:event_DEPARTAMENTOSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNBUSCARIMAGEN;
    public javax.swing.JComboBox<String> DEPARTAMENTOS;
    public javax.swing.JButton DETECCIONHUELLA;
    public javax.swing.JLabel LblMostrarHuella;
    public javax.swing.JLabel LblfotoPerfil;
    public javax.swing.JComboBox<String> MUNICIPIOS;
    public javax.swing.JButton botonActualizarEmpleado;
    public javax.swing.JComboBox<String> cargo;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField correo;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField documento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea mensajeHuella;
    private javax.swing.JTextField primer_apellido;
    private javax.swing.JTextField primer_nombre;
    private javax.swing.JTextField segundo_apellido;
    private javax.swing.JTextField segundo_nombre;
    public javax.swing.JComboBox<String> sexo;
    private javax.swing.JTextField telefono;
    public javax.swing.JComboBox<String> tipoDocumento;
    // End of variables declaration//GEN-END:variables
}
