/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.GenerarExcel;
import control.SQLEmpleados;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jack
 */
public class GenerarReportes extends javax.swing.JFrame {

    SQLEmpleados SQL = new SQLEmpleados(this);
    public JFrame parentFrame = new JFrame();
    public DefaultTableModel TABLAGENERARREPORTES;
    public JFileChooser saveFile = new JFileChooser();
    DateFormat DF = new SimpleDateFormat("yyyy-MM-dd");
    private String TITULO = "FORMATO DE REPORTE PARA IMPRESION DEL NÚMERO DE HORAS PRESTADAS"
            + " POR EMPLEADO INFORMACIÓN INDIVIDUAL\n";

    /**
     * Creates new form GenerarReportes
     */
    public GenerarReportes() {
        //TABLAGENERARREPORTES = new DefaultTableModel(new Object[]{"Documento","Nombre","Horas Mensuales","Horas Semanales","Horas diarias"},0);
        super("Generar Reportes");
        initComponents();
        this.tablero.setEditable(false);
        this.BtndescargarPDF.setEnabled(false);
        SQL.obtenerTipoDocumentoParaReporte();
        this.setDefaultCloseOperation(GenerarReportes.HIDE_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    private void obtenerDatos() {
        if (!this.buscar.equals("")) {
            if (this.fechaInicial.getDate() == null || this.fechaInicial.getDate() == null) {
                JOptionPane.showMessageDialog(null, "¡Debe llenar todos los campos de Fecha!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (SQL.validarEmpleadoParaReporte(this.tipo_documento.getSelectedItem().toString(),
                        this.buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate())) != false) {
                    String mensaje = "";
                    mensaje += SQL.ImprimirAsistencias(this.tipo_documento.getSelectedItem().toString(),
                            this.buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate()));
                    this.tablero.setText(mensaje);
                    this.BtndescargarPDF.setEnabled(true);
                } else {
                    JOptionPane.showInternalMessageDialog(null, "¡No se encontro el empleado en la fecha establecida!", "Mensaje", JOptionPane.WARNING_MESSAGE);
                    this.tablero.setText("");
                }
            }
        } else {
            JOptionPane.showInternalMessageDialog(null, "Debe digitar el documento del empleado", "Mensaje", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANELPRINCIPAL = new javax.swing.JPanel();
        tipo_documento = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        BtndescargarPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PANELPRINCIPAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANELPRINCIPAL.add(tipo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 174, -1));

        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        PANELPRINCIPAL.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 159, -1));

        jLabel1.setText("Tipo documento      ");
        PANELPRINCIPAL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("TABLA DE REPORTES DE HORARIOS");
        PANELPRINCIPAL.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 260, -1));
        PANELPRINCIPAL.add(fechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 160, -1));

        jLabel3.setText("Fecha inicial");
        PANELPRINCIPAL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 84, -1));

        jLabel4.setText("Fecha final");
        PANELPRINCIPAL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 100, -1));
        PANELPRINCIPAL.add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 170, -1));

        jLabel5.setText("Documento");
        PANELPRINCIPAL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 105, -1));

        BtndescargarPDF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtndescargarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf32px.png"))); // NOI18N
        BtndescargarPDF.setText(" PDF");
        BtndescargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndescargarPDFActionPerformed(evt);
            }
        });
        PANELPRINCIPAL.add(BtndescargarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, 110, -1));

        tablero.setColumns(20);
        tablero.setRows(5);
        jScrollPane1.setViewportView(tablero);

        PANELPRINCIPAL.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1030, 250));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Excel_2013_23480.png"))); // NOI18N
        jButton1.setText("EXCEL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        PANELPRINCIPAL.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PANELPRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELPRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        this.obtenerDatos();
    }//GEN-LAST:event_buscarActionPerformed

    private void BtndescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndescargarPDFActionPerformed
        // TODO add your handling code here:
        String desktopPath = System.getProperty("user.home") + "/Desktop/";
        desktopPath.replace("\\", "/");
        SQL.ImprimirAsistenciasReportes(this.tipo_documento.getSelectedItem().toString(),
                this.buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate()),
                desktopPath + this.buscar.getText() + ".pdf");
        // GenerarPDF g = new GenerarPDF(SQL.tituloReporte+SQL.usuarioReporte,SQL.mensaje2,desktopPath+this.buscar.getText()+".pdf");

    }//GEN-LAST:event_BtndescargarPDFActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        GenerarExcel excel = new GenerarExcel();
        try {
            excel.crearExcel(buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtndescargarPDF;
    private javax.swing.JPanel PANELPRINCIPAL;
    private javax.swing.JTextField buscar;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea tablero;
    public javax.swing.JComboBox<String> tipo_documento;
    // End of variables declaration//GEN-END:variables
}
