/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.GenerarExcel;
import control.SQLEmpleados;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jack
 */
public class GenerarReportes extends javax.swing.JFrame {

    SQLEmpleados SQL = new SQLEmpleados(this);
    public JFrame parentFrame = new JFrame();
    public DefaultTableModel TABLAGENERARREPORTES;
    public JFileChooser saveFile = new JFileChooser();
    DateFormat DF = new SimpleDateFormat("yyyy-MM-dd");
    private String TITULO = "FORMATO DE REPORTE PARA IMPRESION DEL NÚMERO DE HORAS PRESTADAS"
            + " POR EMPLEADO INFORMACIÓN INDIVIDUAL\n";

    /**
     * Creates new form GenerarReportes
     */
    public GenerarReportes() {
        //TABLAGENERARREPORTES = new DefaultTableModel(new Object[]{"Documento","Nombre","Horas Mensuales","Horas Semanales","Horas diarias"},0);
        super("Generar Reportes");
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        this.tablero.setEditable(false);
        this.BtndescargarPDF.setEnabled(false);
        this.BtndescargarExcel.setEnabled(false);
        SQL.obtenerTipoDocumentoParaReporte();
        this.setDefaultCloseOperation(GenerarReportes.HIDE_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    private void obtenerDatos() {
        if (!this.buscar.equals("")) {
            if (this.fechaInicial.getDate() == null || this.fechaInicial.getDate() == null) {
                JOptionPane.showMessageDialog(null, "¡Debe llenar todos los campos de Fecha!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (SQL.validarEmpleadoParaReporte(this.tipo_documento.getSelectedItem().toString(),
                        this.buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate())) != false) {
                    String mensaje = "";
                    mensaje += SQL.ImprimirAsistencias(this.tipo_documento.getSelectedItem().toString(),
                            this.buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate()));
                    this.tablero.setText(mensaje);
                    this.BtndescargarPDF.setEnabled(true);
                    this.BtndescargarExcel.setEnabled(true);
                } else {
                    JOptionPane.showInternalMessageDialog(null, "¡No se encontro el empleado en la fecha establecida!", "Mensaje", JOptionPane.WARNING_MESSAGE);
                    this.tablero.setText("");
                }
            }
        } else {
            JOptionPane.showInternalMessageDialog(null, "Debe digitar el documento del empleado", "Mensaje", JOptionPane.WARNING_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PANELPRINCIPAL = new javax.swing.JPanel();
        tipo_documento = new javax.swing.JComboBox<>();
        buscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        fechaInicial = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        BtndescargarPDF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablero = new javax.swing.JTextArea();
        BtndescargarExcel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PANELPRINCIPAL.setBackground(new java.awt.Color(255, 255, 255));
        PANELPRINCIPAL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PANELPRINCIPAL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PANELPRINCIPAL.add(tipo_documento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 174, 30));

        buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        PANELPRINCIPAL.add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 170, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Tipo documento      ");
        PANELPRINCIPAL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 120, -1));

        fechaInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));
        PANELPRINCIPAL.add(fechaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 160, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fecha inicial");
        PANELPRINCIPAL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 360, 90, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fecha final");
        PANELPRINCIPAL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 110, -1));

        fechaFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(52, 152, 219)));
        PANELPRINCIPAL.add(fechaFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 170, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Documento");
        PANELPRINCIPAL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 110, -1));

        BtndescargarPDF.setBackground(new java.awt.Color(255, 255, 255));
        BtndescargarPDF.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtndescargarPDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pdf32px.png"))); // NOI18N
        BtndescargarPDF.setText(" PDF");
        BtndescargarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndescargarPDFActionPerformed(evt);
            }
        });
        PANELPRINCIPAL.add(BtndescargarPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 110, 40));

        tablero.setColumns(20);
        tablero.setRows(5);
        jScrollPane1.setViewportView(tablero);

        PANELPRINCIPAL.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1030, 250));

        BtndescargarExcel.setBackground(new java.awt.Color(255, 255, 255));
        BtndescargarExcel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtndescargarExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Excel_2013_23480.png"))); // NOI18N
        BtndescargarExcel.setText("EXCEL");
        BtndescargarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtndescargarExcelActionPerformed(evt);
            }
        });
        PANELPRINCIPAL.add(BtndescargarExcel, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 110, 40));

        jPanel1.setBackground(new java.awt.Color(255, 203, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("TABLA DE REPORTES DE HORARIOS");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PANELPRINCIPAL.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(PANELPRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, 1077, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PANELPRINCIPAL, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        if (this.buscar.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "¡Debe digitar el documento!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
        } else {
            if (this.fechaInicial.getDate() == null || this.fechaFinal.getDate() == null) {
                JOptionPane.showMessageDialog(null, "¡Debe establecer el rango de fechas requeridas!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (this.fechaInicial.getDate().after(this.fechaFinal.getDate())) {
                    JOptionPane.showMessageDialog(null, "¡La fecha inicial debe ser menor a la fecha final!", "Mensaje", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    this.obtenerDatos();
                }
            }
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void BtndescargarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndescargarPDFActionPerformed
        // TODO add your handling code here:
        String desktopPath = System.getProperty("user.home") + "/Desktop/";
        desktopPath.replace("\\", "/");
        SQL.ImprimirAsistenciasReportes(this.tipo_documento.getSelectedItem().toString(),
                this.buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate()),
                desktopPath + this.buscar.getText() + ".pdf");
        // GenerarPDF g = new GenerarPDF(SQL.tituloReporte+SQL.usuarioReporte,SQL.mensaje2,desktopPath+this.buscar.getText()+".pdf");

    }//GEN-LAST:event_BtndescargarPDFActionPerformed

    private void BtndescargarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtndescargarExcelActionPerformed
        // TODO add your handling code here:
        GenerarExcel excel = new GenerarExcel();
        try {
            excel.crearExcel(buscar.getText(), DF.format(this.fechaInicial.getDate()), DF.format(this.fechaFinal.getDate()));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error", ex.getMessage(), JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtndescargarExcelActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GenerarReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GenerarReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtndescargarExcel;
    private javax.swing.JButton BtndescargarPDF;
    private javax.swing.JPanel PANELPRINCIPAL;
    private javax.swing.JTextField buscar;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea tablero;
    public javax.swing.JComboBox<String> tipo_documento;
    // End of variables declaration//GEN-END:variables
}
