/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.SQLEmpleados;
import java.awt.Image;
import java.time.LocalTime;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import modelo.Empleados;

/**
 *
 * @author jack
 */
public class Index extends javax.swing.JFrame {
        
    
    public Empleados usuario_activo = new Empleados();
    public boolean flagEditar = false;
    SQLEmpleados SQL = new SQLEmpleados();
    public int bandera = 0;

    /**
     * Creates new form login
     */
    public Index(){        
        initComponents();
        this.setDefaultCloseOperation(Index.EXIT_ON_CLOSE);
        Index.setDefaultLookAndFeelDecorated(true);
        JDialog.setDefaultLookAndFeelDecorated(true);
        this.menu_empleados.setVisible(false);
        this.menu_opciones.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setSize(480,370);
        this.setResizable(true);
        verificarSalidas();
    }
    
    private void verificarSalidas(){
//        if(LocalTime.now().isAfter(LocalTime.of(18,15,59))){
             SQL.asignarSalidaDeUsuariosPMSistema();
//        }
//        if(LocalTime.now().isAfter(LocalTime.of(12,45,59)) && LocalTime.now().isBefore(LocalTime.of(23,59,59))){
//             SQL.asignarSalidaDeUsuariosAMSistema();         
//        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu_empleados = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menu_iniciar_sesion = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();
        menu_opciones = new javax.swing.JMenu();
        registrar_asistencias = new javax.swing.JMenuItem();
        consultar_asistencias = new javax.swing.JMenuItem();
        generar_reportes = new javax.swing.JMenuItem();
        cargos = new javax.swing.JMenuItem();
        cierre_sistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setText("Inicio");

        jMenuItem2.setText("Generar Asistencia");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menu_empleados.setText("Empleados");

        jMenuItem3.setText("Agregar nuevo");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menu_empleados.add(jMenuItem3);

        jMenuItem4.setText("Editar Empleado");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu_empleados.add(jMenuItem4);

        jMenuItem1.setText("Lista de Empleados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu_empleados.add(jMenuItem1);

        jMenu1.add(menu_empleados);

        menu_iniciar_sesion.setText("Iniciar Sesión");
        menu_iniciar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_iniciar_sesionActionPerformed(evt);
            }
        });
        jMenu1.add(menu_iniciar_sesion);

        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        jMenu1.add(menu_salir);

        jMenuBar1.add(jMenu1);

        menu_opciones.setText("Opciones");

        registrar_asistencias.setText("Registrar Asistencias");
        registrar_asistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_asistenciasActionPerformed(evt);
            }
        });
        menu_opciones.add(registrar_asistencias);

        consultar_asistencias.setText("Consultar Asistencias");
        consultar_asistencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultar_asistenciasActionPerformed(evt);
            }
        });
        menu_opciones.add(consultar_asistencias);

        generar_reportes.setText("Generar Reportes");
        generar_reportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generar_reportesActionPerformed(evt);
            }
        });
        menu_opciones.add(generar_reportes);

        cargos.setText("Cargos");
        cargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargosActionPerformed(evt);
            }
        });
        menu_opciones.add(cargos);

        cierre_sistema.setText("Cierres del Sistema PM");
        cierre_sistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cierre_sistemaActionPerformed(evt);
            }
        });
        menu_opciones.add(cierre_sistema);

        jMenuBar1.add(menu_opciones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_iniciar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_iniciar_sesionActionPerformed
        // TODO add your handling code here:
        IniciarSesion IN = new IniciarSesion(this,usuario_activo);
        IN.setVisible(true);   
    }//GEN-LAST:event_menu_iniciar_sesionActionPerformed

    private void registrar_asistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_asistenciasActionPerformed
        // TODO add your handling code here:
        RegistrarAsistencias NUEVAASISTENCIA = new RegistrarAsistencias(this);
        NUEVAASISTENCIA.setVisible(true);
    }//GEN-LAST:event_registrar_asistenciasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        AgregarEmpleados nuevoEmpleado = new AgregarEmpleados();
        nuevoEmpleado.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void consultar_asistenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultar_asistenciasActionPerformed
        // TODO add your handling code here:
        ConsultarAsistencias CA = new ConsultarAsistencias();
        CA.setVisible(true);
    }//GEN-LAST:event_consultar_asistenciasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:   
        EditarEmpleados ED = new EditarEmpleados();
        ED.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void generar_reportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generar_reportesActionPerformed
        // TODO add your handling code here:
        GenerarReportes GR = new GenerarReportes();
        GR.setVisible(true);
    }//GEN-LAST:event_generar_reportesActionPerformed

    private void cargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargosActionPerformed
        // TODO add your handling code here:
        AgregarTipoCargos cargos = new AgregarTipoCargos();
        cargos.setVisible(true);
    }//GEN-LAST:event_cargosActionPerformed

    private void cierre_sistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cierre_sistemaActionPerformed
        // TODO add your handling code here:
        AdministrarSalidaPorSistema salidasSistema = new AdministrarSalidaPorSistema();
        salidasSistema.setVisible(true);
    }//GEN-LAST:event_cierre_sistemaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        VisualizarEmpleados VE = new VisualizarEmpleados();
        VE.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        LoginHuella LOGINHUELLA = new LoginHuella();
        LOGINHUELLA.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            //here you can put the selected theme class name in JTattoo
//            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
//
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }

try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }

//        UIManager.setLookAndFeel("com.seaglasslookandfeel.seaGlassLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem cargos;
    public javax.swing.JMenuItem cierre_sistema;
    public javax.swing.JMenuItem consultar_asistencias;
    public javax.swing.JMenuItem generar_reportes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JMenu menu_empleados;
    public javax.swing.JMenuItem menu_iniciar_sesion;
    public javax.swing.JMenu menu_opciones;
    private javax.swing.JMenuItem menu_salir;
    public javax.swing.JMenuItem registrar_asistencias;
    // End of variables declaration//GEN-END:variables
}
