/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.HuellaLogin;
import control.SQLEmpleados;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;

/**
 *
 * @author juliancc
 */
public class LoginHuella extends javax.swing.JFrame {

    SQLEmpleados SQL = new SQLEmpleados(this);
    public String ID;

    /**
     * Creates new form LoginHuella
     */
    public LoginHuella() {
        setUndecorated(true);
        getRootPane().setWindowDecorationStyle(JRootPane.NONE);
        initComponents();
        this.horaTitulo();
        this.boton_registrar_ingreso.setEnabled(false);
        this.registrar_salida.setEnabled(false);
        this.mensajeHuella.setEnabled(false);
        this.setDefaultCloseOperation(ConsultarAsistencias.HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    public void cerrarVentana() {
        this.setDefaultCloseOperation(ConsultarAsistencias.HIDE_ON_CLOSE);
    }

    public void noCerrarVentana() {
        this.setDefaultCloseOperation(ConsultarAsistencias.DO_NOTHING_ON_CLOSE);
    }

    private void horaTitulo() {
        if (LocalTime.now().isAfter(LocalTime.NOON)) {
            titulo_tiempo.setText("REGISTRAR ASISTENCIAS HORARIO DE LA TARDE");
        }
    }

    public void verificarIngresos(int documento) {
        if (SQL.consultarIngresoDeUsuariosAM(documento)) {
            if (SQL.consultarSalidaDeUsuariosPM(documento)) {
                this.boton_registrar_ingreso.setEnabled(false);
                this.registrar_salida.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Este empleado ya completo la asistencia del dia", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.boton_registrar_ingreso.setEnabled(false);
                this.registrar_salida.setEnabled(true);
            }
        } else {
            this.boton_registrar_ingreso.setEnabled(true);
            this.registrar_salida.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblMostrarHuella = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DOCUMENTOEMPLEADO = new javax.swing.JLabel();
        NOMBREEMPLEADO = new javax.swing.JLabel();
        CARGOEMPLEADO = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MUNICIPIOEMPLEADO = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajeHuella = new javax.swing.JTextArea();
        BTNINICIARHUELLA = new javax.swing.JButton();
        boton_registrar_ingreso = new javax.swing.JButton();
        registrar_salida = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        titulo_tiempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblMostrarHuella.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblMostrarHuella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_profile.png"))); // NOI18N
        LblMostrarHuella.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(LblMostrarHuella, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 180));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Información Empleado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setText("DOCUMENTO:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setText("NOMBRE:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel4.setText("CARGO:");

        DOCUMENTOEMPLEADO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NOMBREEMPLEADO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        CARGOEMPLEADO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel5.setText("MUNICIPIO:");

        MUNICIPIOEMPLEADO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CARGOEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(NOMBREEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DOCUMENTOEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MUNICIPIOEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(DOCUMENTOEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(NOMBREEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(CARGOEMPLEADO, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MUNICIPIOEMPLEADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 446, 170));

        mensajeHuella.setColumns(20);
        mensajeHuella.setRows(5);
        jScrollPane1.setViewportView(mensajeHuella);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 446, 80));

        BTNINICIARHUELLA.setBackground(new java.awt.Color(255, 255, 255));
        BTNINICIARHUELLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BTNINICIARHUELLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fingerprint_32PX.png"))); // NOI18N
        BTNINICIARHUELLA.setText("Iniciar Detección de Huella");
        BTNINICIARHUELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNINICIARHUELLAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNINICIARHUELLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 271, 60));

        boton_registrar_ingreso.setBackground(new java.awt.Color(255, 255, 255));
        boton_registrar_ingreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_registrar_ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cronometro32px.png"))); // NOI18N
        boton_registrar_ingreso.setText("Registrar ingreso");
        boton_registrar_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrar_ingresoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_registrar_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 209, 51));

        registrar_salida.setBackground(new java.awt.Color(255, 255, 255));
        registrar_salida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrar_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar-clock-icon32px.png"))); // NOI18N
        registrar_salida.setText("Registrar salida");
        registrar_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_salidaActionPerformed(evt);
            }
        });
        jPanel1.add(registrar_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, 227, 51));

        jPanel3.setBackground(new java.awt.Color(31, 58, 147));

        titulo_tiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo_tiempo.setForeground(new java.awt.Color(255, 255, 255));
        titulo_tiempo.setText("AGREGAR ASISTENCIAS HORARIO DE LA MAÑANA");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(titulo_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addComponent(titulo_tiempo))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNINICIARHUELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNINICIARHUELLAActionPerformed
        // TODO add your handling code here:
        int respuesta;
        respuesta = JOptionPane.showOptionDialog(null, "¿Esta seguro que desea continuar?", "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            this.boton_registrar_ingreso.setEnabled(false);
            this.registrar_salida.setEnabled(false);
            ImageIcon imagen = new ImageIcon("..//imagenes/user_profile.png");
            this.LblMostrarHuella.setIcon(new ImageIcon(imagen.getImage().getScaledInstance(this.LblMostrarHuella.getWidth(),
                    this.LblMostrarHuella.getHeight(), java.awt.Image.SCALE_DEFAULT)));
            this.DOCUMENTOEMPLEADO.setText(null);
            this.NOMBREEMPLEADO.setText(null);
            this.CARGOEMPLEADO.setText(null);
            this.mensajeHuella.setText("");
            this.MUNICIPIOEMPLEADO.setText("");
            this.BTNINICIARHUELLA.setEnabled(false);
            this.noCerrarVentana();
            HuellaLogin HUELLA = new HuellaLogin(this);
            HUELLA.Iniciar();
            HUELLA.start();
            HUELLA.estadoHuellas();
        }
    }//GEN-LAST:event_BTNINICIARHUELLAActionPerformed

    private void boton_registrar_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrar_ingresoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(this.ID);
        Date horaIngresoAM = new Date();
        DateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if (SQL.RegistrarHoraIngresoAM(id, formatofecha.format(horaIngresoAM))) {
            JOptionPane.showMessageDialog(null, "¡Asistencia confirmada satisfactoriamente!");
            this.boton_registrar_ingreso.setEnabled(false);
            this.registrar_salida.setEnabled(true);
        }
    }//GEN-LAST:event_boton_registrar_ingresoActionPerformed

    private void registrar_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_salidaActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(this.ID);
        Date horasalidaPM = new Date();
        DateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if (SQL.RegistrarHoraSalidaPM(id, formatofecha.format(horasalidaPM))) {
            JOptionPane.showMessageDialog(null, "¡Salida confirmada satisfactoriamente!");
            this.registrar_salida.setEnabled(false); 
        }
    }//GEN-LAST:event_registrar_salidaActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginHuella().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTNINICIARHUELLA;
    public javax.swing.JLabel CARGOEMPLEADO;
    public javax.swing.JLabel DOCUMENTOEMPLEADO;
    public javax.swing.JLabel LblMostrarHuella;
    public javax.swing.JLabel MUNICIPIOEMPLEADO;
    public javax.swing.JLabel NOMBREEMPLEADO;
    private javax.swing.JButton boton_registrar_ingreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea mensajeHuella;
    private javax.swing.JButton registrar_salida;
    private static javax.swing.JLabel titulo_tiempo;
    // End of variables declaration//GEN-END:variables
}
