/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.HuellaDigital;
import control.HuellaDigitalAsistencias;
import control.SQLEmpleados;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jack
 */
public class RegistrarAsistencias extends javax.swing.JFrame {

    Index index;
    SQLEmpleados SQL = new SQLEmpleados(this);

    /**
     * Creates new form RegistrarAsistencias
     */
    public RegistrarAsistencias() {
        initComponents();
        //this.verificarIngresos();
    }

    public RegistrarAsistencias(Index index) {
        initComponents();
        this.horaTitulo();
        this.boton_registrar_ingreso.setEnabled(false);
        this.registrar_salida.setEnabled(false);
        this.mensajeHuella.setEditable(false);
        this.setDefaultCloseOperation(RegistrarAsistencias.HIDE_ON_CLOSE);
        this.index = index;
        //this.verificarIngresos();    
        SQL.obtenerFotoRegistrarAsistencias(this.index.usuario_activo.getDOCUMENTO());
        this.DOCUMENTO.setText(this.index.usuario_activo.getDOCUMENTO());
        this.NOMBRE.setText(this.index.usuario_activo.getPRIMER_NOMBRE() + " "
                + this.index.usuario_activo.getSEGUNDO_NOMBRE() + " "
                + this.index.usuario_activo.getPRIMER_APELLIDO() + " "
                + this.index.usuario_activo.getSEGUNDO_APELLIDO());
        this.DIRECCION.setText(this.index.usuario_activo.getDIRECCION());
        this.TELEFONO.setText(this.index.usuario_activo.getTELEFONO());
        this.CORREO.setText(this.index.usuario_activo.getCORREO());
        this.setResizable(false);
        this.setLocationRelativeTo(null);
    }

    public void noCerrarVentana() {
        this.setDefaultCloseOperation(RegistrarAsistencias.DO_NOTHING_ON_CLOSE);
    }

    public void cerrarVentana() {
        this.setDefaultCloseOperation(RegistrarAsistencias.HIDE_ON_CLOSE);
    }

    private void horaTitulo() {
        if (LocalTime.now().isAfter(LocalTime.NOON)) {
            titulo_tiempo.setText("REGISTRAR ASISTENCIAS HORARIO DE LA TARDE");
        }
    }

    public void verificarIngresos(int documento) {
        if (SQL.consultarIngresoDeUsuariosAM(documento)) {
            if (SQL.consultarSalidaDeUsuariosPM(documento)) {
                this.boton_registrar_ingreso.setEnabled(false);
                this.registrar_salida.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Este empleado ya completo la asistencia del dia", "", JOptionPane.INFORMATION_MESSAGE);
            } else {
                this.boton_registrar_ingreso.setEnabled(false);
                this.registrar_salida.setEnabled(true);
            }
        } else {
            this.boton_registrar_ingreso.setEnabled(true);
            this.registrar_salida.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo_tiempo = new javax.swing.JLabel();
        boton_registrar_ingreso = new javax.swing.JButton();
        registrar_salida = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        CORREO = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TELEFONO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DIRECCION = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NOMBRE = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DOCUMENTO = new javax.swing.JLabel();
        LblFotoPerfil = new javax.swing.JPanel();
        LblImagenPerfil = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mensajeHuella = new javax.swing.JTextArea();
        DETECCIONHUELLA = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo_tiempo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo_tiempo.setText("AGREGAR ASISTENCIAS HORARIO DE LA MAÑANA");
        jPanel1.add(titulo_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 400, -1));

        boton_registrar_ingreso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        boton_registrar_ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cronometro32px.png"))); // NOI18N
        boton_registrar_ingreso.setText("Registrar ingreso");
        boton_registrar_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_registrar_ingresoActionPerformed(evt);
            }
        });
        jPanel1.add(boton_registrar_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 200, 60));

        registrar_salida.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        registrar_salida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendar-clock-icon32px.png"))); // NOI18N
        registrar_salida.setText("Registrar Salida");
        registrar_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrar_salidaActionPerformed(evt);
            }
        });
        jPanel1.add(registrar_salida, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, 190, 60));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Información Empleado"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("CORREO:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 223, -1, -1));

        CORREO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(CORREO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 280, 30));

        jLabel4.setText("TELÉFONO:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 182, -1, -1));

        TELEFONO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(TELEFONO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 280, 30));

        jLabel3.setText("DIRECCIÓN:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 140, -1, -1));

        DIRECCION.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(DIRECCION, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 280, 30));

        jLabel2.setText("NOMBRE:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 94, -1, 20));

        NOMBRE.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 280, 30));

        jLabel6.setText("DOCUMENTO:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 48, -1, 30));

        DOCUMENTO.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.add(DOCUMENTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 280, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 400, 270));

        LblFotoPerfil.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Imagen Perfil", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.ABOVE_TOP));

        LblImagenPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblImagenPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user_profile.png"))); // NOI18N
        LblImagenPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout LblFotoPerfilLayout = new javax.swing.GroupLayout(LblFotoPerfil);
        LblFotoPerfil.setLayout(LblFotoPerfilLayout);
        LblFotoPerfilLayout.setHorizontalGroup(
            LblFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblImagenPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
        );
        LblFotoPerfilLayout.setVerticalGroup(
            LblFotoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LblImagenPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
        );

        jPanel1.add(LblFotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 250, 280));

        mensajeHuella.setColumns(20);
        mensajeHuella.setRows(5);
        jScrollPane2.setViewportView(mensajeHuella);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 660, 90));

        DETECCIONHUELLA.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DETECCIONHUELLA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fingerprint_32PX.png"))); // NOI18N
        DETECCIONHUELLA.setText("Iniciar Detección de huella");
        DETECCIONHUELLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DETECCIONHUELLAActionPerformed(evt);
            }
        });
        jPanel1.add(DETECCIONHUELLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 270, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_registrar_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_registrar_ingresoActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(this.index.usuario_activo.getID());
        Date horaIngresoAM = new Date();
        DateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if (SQL.RegistrarHoraIngresoAM(id, formatofecha.format(horaIngresoAM))) {
            JOptionPane.showMessageDialog(null, "¡Asistencia confirmada satisfactoriamente!");
            this.boton_registrar_ingreso.setEnabled(false);
            this.registrar_salida.setEnabled(true);
        }
    }//GEN-LAST:event_boton_registrar_ingresoActionPerformed

    private void registrar_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrar_salidaActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(this.index.usuario_activo.getID());
        Date horasalidaPM = new Date();
        DateFormat formatofecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        if (SQL.RegistrarHoraSalidaPM(id, formatofecha.format(horasalidaPM))) {
            JOptionPane.showMessageDialog(null, "¡Salida confirmada satisfactoriamente!");
            this.registrar_salida.setEnabled(false);
        }
    }//GEN-LAST:event_registrar_salidaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        this.HUELLA.Iniciar();
//        this.HUELLA.start();
//        this.HUELLA.estadoHuellas();
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void DETECCIONHUELLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DETECCIONHUELLAActionPerformed
        // TODO add your handling code here:
        int respuesta;
        respuesta = JOptionPane.showOptionDialog(null, "¿Esta seguro que desea continuar?", "Mensaje", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
        if (respuesta == JOptionPane.YES_NO_OPTION) {
            this.noCerrarVentana();
            this.registrar_salida.setEnabled(false);
            this.boton_registrar_ingreso.setEnabled(false);
            HuellaDigitalAsistencias HUELLA = new HuellaDigitalAsistencias(this);
            this.DETECCIONHUELLA.setEnabled(false);
            HUELLA.documentousuario = this.index.usuario_activo.getDOCUMENTO();
            HUELLA.Iniciar();
            HUELLA.start();
            HUELLA.estadoHuellas();
            this.DETECCIONHUELLA.setEnabled(false);
        }
    }//GEN-LAST:event_DETECCIONHUELLAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarAsistencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CORREO;
    public javax.swing.JButton DETECCIONHUELLA;
    private javax.swing.JLabel DIRECCION;
    private javax.swing.JLabel DOCUMENTO;
    public javax.swing.JPanel LblFotoPerfil;
    public javax.swing.JLabel LblImagenPerfil;
    private javax.swing.JLabel NOMBRE;
    private javax.swing.JLabel TELEFONO;
    public javax.swing.JButton boton_registrar_ingreso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea mensajeHuella;
    private javax.swing.JButton registrar_salida;
    private static javax.swing.JLabel titulo_tiempo;
    // End of variables declaration//GEN-END:variables
}
