/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.SQLEmpleados;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juliancc
 */
public class VisualizarEmpleados extends javax.swing.JFrame {
public DefaultTableModel TABLA;
SQLEmpleados SQL = new SQLEmpleados(this);
    /**
     * Creates new form VisualizarEmpleados
     */
    public VisualizarEmpleados() {
        TABLA = new DefaultTableModel(new Object[]{"DOCUMENTO","NOMBRE EMPLEADO","CARGO","DIRECCION","TELEFONO","CORREO"},0){    
            @Override public boolean isCellEditable(int row, int col){
                return false;
            }            
        };
        initComponents();
        this.setDefaultCloseOperation(Index.HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        this.setResizable(true);
        SQL.obtenerTipoDocumentoListaEmpleados();
        SQL.obtenerListaEmpleados();
        SQL.obtenerTotalEmpleados();
    }

            public void borrarFilasTabla(){
            while(this.TABLA.getRowCount()>0){
                for(int j=0;j<this.TABLA.getRowCount();j++){
                        this.TABLA.removeRow(j);
                }
            this.TABLAPRINCIPAL.repaint();
            }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tipoDocumento = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        documento = new javax.swing.JTextField();
        mostrarTodosEmpleados = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAPRINCIPAL = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        imagenPerfil = new javax.swing.JLabel();
        LblTotalEmpleados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        tipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoDocumentoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo Documento");

        documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoActionPerformed(evt);
            }
        });

        mostrarTodosEmpleados.setText("MostrarTodos los Empleados");
        mostrarTodosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarTodosEmpleadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(tipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(documento, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(mostrarTodosEmpleados)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(documento, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrarTodosEmpleados))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 830, 120));

        TABLAPRINCIPAL.setModel(TABLA);
        TABLAPRINCIPAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TABLAPRINCIPAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLAPRINCIPALMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLAPRINCIPAL);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1020, 250));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TABLA DE EMPLEADOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 323, 32));

        imagenPerfil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(imagenPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 180, 150));

        LblTotalEmpleados.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jPanel1.add(LblTotalEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 163, 150, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 1060, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoDocumentoActionPerformed

    private void TABLAPRINCIPALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLAPRINCIPALMouseClicked
        // TODO add your handling code here:
        if(TABLA.getRowCount() > 0){
            String documento = this.TABLA.getValueAt(this.TABLAPRINCIPAL.getSelectedRow(),0).toString();
            SQL.obtenerFotoListaEmpleados(documento);
        }else{
        JOptionPane.showMessageDialog(null,"¡Debe seleccionar una fila de la tabla!","Mensaje",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_TABLAPRINCIPALMouseClicked

    private void documentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoActionPerformed
        // TODO add your handling code here:
        if(!this.documento.equals("")){
            this.borrarFilasTabla();
            SQL.obtenerUsuarioListaEmpleados(this.documento.getText(), tipoDocumento.getSelectedItem().toString());
        }else{
            JOptionPane.showMessageDialog(null,"¡Debe digitar un documento!","Mensaje",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_documentoActionPerformed

    private void mostrarTodosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarTodosEmpleadosActionPerformed
        // TODO add your handling code here:
        if(this.mostrarTodosEmpleados.isSelected()){
            this.documento.setText("");
            this.borrarFilasTabla();
            SQL.obtenerListaEmpleados();
        }
    }//GEN-LAST:event_mostrarTodosEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LblTotalEmpleados;
    private javax.swing.JTable TABLAPRINCIPAL;
    private javax.swing.JTextField documento;
    public javax.swing.JLabel imagenPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox mostrarTodosEmpleados;
    public javax.swing.JComboBox<String> tipoDocumento;
    // End of variables declaration//GEN-END:variables
}
